site_name: DistributedAutonomousExchange.com
theme:
  name: material
  theme:
  favicon: /assets/images/favicon.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    scheme: slate
    primary: white
    accent: red